---
# tasks file for ansible-docker-swarm

- include: pre-reqs.yml
  when: docker_swarm_config_pre_requisites

- include: cluster.yml

- include: networks.yml
  when: >
        docker_swarm_config_networks and
        docker_swarm_networks is defined

- include: settings.yml
  when: docker_swarm_config_settings
